[project]
name = "nullroom"
version = "0.2.0"
description = "Disposable chat rooms that leave no trace."
authors = [
    {
        email="cloner.bl12@gmail.com",
        name="Jack Scott"
    }
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[tool.fastapi]
    entrypoint = "main:nullroom"
